### ISSUE TITLE
Search fails if text includes single quote(s)

### ISSUE THREAD

**Issue by m1foley** [rgrinberg/vim-operator-gsearch#2]
My .vimrc:
```rc
map g/ <Plug>(operator-ag)
```

Steps to recreate:
1. Use `v` to select text that includes quote(s): `isn't`
2. Type `g/`

Bug: vim-operator-gsearch fails to find the text and says:
```
No matches for "-Q 'isn\'\''t'"
```

**Comment by rgrinberg** [comment]
I've fixed this particular issue but I know that escaping is unfortunately wonky. Please report any other bugs you find.

**Comment by m1foley** [comment]
Works now. Thanks! :ok_hand:
